<?php
/**
 * laravelfr
 *
 * @author Julien Tant - Craftyx <julien@craftyx.fr>
 */

namespace LaravelFranceOld\Exceptions;

use Exception;

class UsernameAlreadyTaken extends \Exception
{
    /**
     * @var string
     */
    private $username;

    public function __construct($message = "", $username = "", $code = 0, Exception $previous = null)
    {
        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
        $this->username = $username;
    }

    /**
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }


}
